# this class loads all the images before use
import pygame
import os

class Cards:

    def __int__(self):
        self.cards = []

    def loadCards(self): #hardcoded instead of proceduraly because with proceduraly, no names could be given to the images.
        self.Corner = pygame.image.load("Corner.png").convert()

        self.H2 = pygame.image.load("H2.png").convert()
        self.H3 = pygame.image.load("H3.png").convert()
        self.H4 = pygame.image.load("H4.png").convert()
        self.H5 = pygame.image.load("H5.png").convert()
        self.H6 = pygame.image.load("H6.png").convert()
        self.H7 = pygame.image.load("H7.png").convert()
        self.H8 = pygame.image.load("H8.png").convert()
        self.H9 = pygame.image.load("H9.png").convert()
        self.H10 = pygame.image.load("H10.png").convert()
        self.HA = pygame.image.load("HA.png").convert()
        self.HJ = pygame.image.load("HJ.png").convert()
        self.HQ = pygame.image.load("HQ.png").convert()
        self.HK = pygame.image.load("HK.png").convert()

        self.K2 = pygame.image.load("K2.png").convert()
        self.K3 = pygame.image.load("K3.png").convert()
        self.K4 = pygame.image.load("K4.png").convert()
        self.K5 = pygame.image.load("K5.png").convert()
        self.K6 = pygame.image.load("K6.png").convert()
        self.K7 = pygame.image.load("K7.png").convert()
        self.K8 = pygame.image.load("K8.png").convert()
        self.K9 = pygame.image.load("K9.png").convert()
        self.K10 = pygame.image.load("K10.png").convert()
        self.KA = pygame.image.load("KA.png").convert()
        self.KJ = pygame.image.load("KJ.png").convert()
        self.KQ = pygame.image.load("KQ.png").convert()
        self.KK = pygame.image.load("KK.png").convert()

        self.R2 = pygame.image.load("R2.png").convert()
        self.R3 = pygame.image.load("R3.png").convert()
        self.R4 = pygame.image.load("R4.png").convert()
        self.R5 = pygame.image.load("R5.png").convert()
        self.R6 = pygame.image.load("R6.png").convert()
        self.R7 = pygame.image.load("R7.png").convert()
        self.R8 = pygame.image.load("R8.png").convert()
        self.R9 = pygame.image.load("R9.png").convert()
        self.R10 = pygame.image.load("R10.png").convert()
        self.RA = pygame.image.load("RA.png").convert()
        self.RJ = pygame.image.load("RJ.png").convert()
        self.RQ = pygame.image.load("RQ.png").convert()
        self.RK = pygame.image.load("RK.png").convert()

        self.S2 = pygame.image.load("S2.png").convert()
        self.S3 = pygame.image.load("S3.png").convert()
        self.S4 = pygame.image.load("S4.png").convert()
        self.S5 = pygame.image.load("S5.png").convert()
        self.S6 = pygame.image.load("S6.png").convert()
        self.S7 = pygame.image.load("S7.png").convert()
        self.S8 = pygame.image.load("S8.png").convert()
        self.S9 = pygame.image.load("S9.png").convert()
        self.S10 = pygame.image.load("S10.png").convert()
        self.SA = pygame.image.load("SA.png").convert()
        self.SJ = pygame.image.load("SJ.png").convert()
        self.SQ = pygame.image.load("SQ.png").convert()
        self.SK = pygame.image.load("SK.png").convert()

    def addCards(self):
        self.cards.append(self.Corner)

        self.cards.append(self.H2)
        self.cards.append(self.H3)
        self.cards.append(self.H4)
        self.cards.append(self.H5)
        self.cards.append(self.H6)
        self.cards.append(self.H7)
        self.cards.append(self.H8)
        self.cards.append(self.H9)
        self.cards.append(self.H10)
        self.cards.append(self.HA)
        self.cards.append(self.HJ)
        self.cards.append(self.HQ)
        self.cards.append(self.HK)

        self.cards.append(self.K2)
        self.cards.append(self.K3)
        self.cards.append(self.K4)
        self.cards.append(self.K5)
        self.cards.append(self.K6)
        self.cards.append(self.K7)
        self.cards.append(self.K8)
        self.cards.append(self.K9)
        self.cards.append(self.K10)
        self.cards.append(self.KA)
        self.cards.append(self.KJ)
        self.cards.append(self.KQ)
        self.cards.append(self.KK)

        self.cards.append(self.R2)
        self.cards.append(self.R3)
        self.cards.append(self.R4)
        self.cards.append(self.R5)
        self.cards.append(self.R6)
        self.cards.append(self.R7)
        self.cards.append(self.R8)
        self.cards.append(self.R9)
        self.cards.append(self.R10)
        self.cards.append(self.RA)
        self.cards.append(self.RJ)
        self.cards.append(self.RQ)
        self.cards.append(self.RK)

        self.cards.append(self.S2)
        self.cards.append(self.S3)
        self.cards.append(self.S4)
        self.cards.append(self.S5)
        self.cards.append(self.S6)
        self.cards.append(self.S7)
        self.cards.append(self.S8)
        self.cards.append(self.S9)
        self.cards.append(self.S10)
        self.cards.append(self.SA)
        self.cards.append(self.SJ)
        self.cards.append(self.SQ)
        self.cards.append(self.SK)

